//
// Created by aven on 31/05/2026.
//

#ifndef CPPCOMPILER_TOKENTYPE_H
#define CPPCOMPILER_TOKENTYPE_H

#define KEYWORD_LIST \
KEYWORD_DEF("int", KW_INT, KW_TYPE) \
KEYWORD_DEF("char", KW_CHAR, KW_TYPE) \
KEYWORD_DEF("short", KW_SHORT, KW_TYPE) \
KEYWORD_DEF("long", KW_LONG, KW_TYPE) \
KEYWORD_DEF("float", KW_FLOAT, KW_TYPE) \
KEYWORD_DEF("double", KW_DOUBLE, KW_TYPE) \
KEYWORD_DEF("wchar_t", KW_WCHAR_T, KW_TYPE) \
KEYWORD_DEF("char8_t", KW_CHAR8_T, KW_TYPE) \
KEYWORD_DEF("char16_t", KW_CHAR16_T, KW_TYPE) \
KEYWORD_DEF("char32_t", KW_CHAR32_T, KW_TYPE) \
KEYWORD_DEF("bool", KW_BOOL, KW_TYPE) \
\
KEYWORD_DEF("true", KW_TRUE, KW_BOOL_LITERAL) \
KEYWORD_DEF("false", KW_FALSE, KW_BOOL_LITERAL) \

#define OPERATOR_LIST \
OPERATOR_DEF("+", OP_PLUS, OP_ARITH) \
OPERATOR_DEF("-", OP_MINUS, OP_ARITH) \
OPERATOR_DEF("/", OP_DIV, OP_ARITH) \
OPERATOR_DEF("*", OP_MULT, OP_ARITH) \
\
OPERATOR_DEF("=", OP_ASSIGN, OP_ASSIGN) \
\
OPERATOR_DEF("==", OP_EQUAL, OP_EQUALITY) \
OPERATOR_DEF("!=", OP_NOT_EQUAL, OP_EQUALITY) \
OPERATOR_DEF("<", OP_LESS_THAN, OP_EQUALITY) \
OPERATOR_DEF("<=", OP_LESS_EQUAL, OP_EQUALITY) \
OPERATOR_DEF(">", OP_GREATER_THAN, OP_EQUALITY) \
OPERATOR_DEF(">=", OP_GREATER_EQUAL, OP_EQUALITY)

enum TokenType {
    NUM,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    IDENTIFIER,
    SEMI_COLON,
    #define KEYWORD_DEF(str, token, cat) token,
    KEYWORD_LIST
    #undef KEYWORD_DEF
    #define OPERATOR_DEF(str, token, cat) token,
    OPERATOR_LIST
    #undef OPERATOR_DEF
};

#endif //CPPCOMPILER_TOKENTYPE_H
