//
// Created by aven on 31/05/2026.
//

#ifndef CPPCOMPILER_TOKENTYPE_H
#define CPPCOMPILER_TOKENTYPE_H

#define TYPE_LIST \
    TYPE_DEF(KW_TYPE) \
    TYPE_DEF(KW_TYPE_KINDA_MAYBE_IDK) \
    TYPE_DEF(KW_BOOL_LITERAL) \
    TYPE_DEF(KW_NULLPTR_LITERAL) \
    TYPE_DEF(OP_ARITH) \
    TYPE_DEF(OP_ASSIGNMENT) \
    TYPE_DEF(OP_EQUALITY) \
    TYPE_DEF(OP_RELATIONAL) \
    TYPE_DEF(OP_LOGIC) \
    TYPE_DEF(OP_ACCESS) \
    TYPE_DEF(LITERAL) \
    TYPE_DEF(IDENTIFIER) \
    TYPE_DEF(PUNCT)

#define KEYWORD_LIST \
    KEYWORD_DEF("int", KW_INT, KW_TYPE) \
    KEYWORD_DEF("char", KW_CHAR, KW_TYPE) \
    KEYWORD_DEF("short", KW_SHORT, KW_TYPE) \
    KEYWORD_DEF("long", KW_LONG, KW_TYPE) \
    KEYWORD_DEF("float", KW_FLOAT, KW_TYPE) \
    KEYWORD_DEF("double", KW_DOUBLE, KW_TYPE) \
    KEYWORD_DEF("wchar_t", KW_WCHAR_T, KW_TYPE) \
    KEYWORD_DEF("char8_t", KW_CHAR8_T, KW_TYPE) \
    KEYWORD_DEF("char16_t", KW_CHAR16_T, KW_TYPE) \
    KEYWORD_DEF("char32_t", KW_CHAR32_T, KW_TYPE) \
    KEYWORD_DEF("bool", KW_BOOL, KW_TYPE) \
    \
    KEYWORD_DEF("void", KW_VOID, KW_TYPE_KINDA_MAYBE_IDK) \
    \
    KEYWORD_DEF("true", KW_TRUE, KW_BOOL_LITERAL) \
    KEYWORD_DEF("false", KW_FALSE, KW_BOOL_LITERAL) \
    \
    KEYWORD_DEF("nullptr", KW_NULLPTR, KW_NULLPTR_LITERAL)

#define OPERATOR_LIST \
    OPERATOR_DEF("+", OP_ADD, OP_ARITH) \
    OPERATOR_DEF("-", OP_SUB, OP_ARITH) \
    OPERATOR_DEF("/", OP_DIV, OP_ARITH) \
    OPERATOR_DEF("*", OP_MULT, OP_ARITH) \
    OPERATOR_DEF("++", OP_INCREMENT, OP_ARITH) \
    OPERATOR_DEF("--", OP_DECREMENT, OP_ARITH) \
    \
    OPERATOR_DEF("=", OP_ASSIGN, OP_ASSIGNMENT) \
    OPERATOR_DEF("+=", OP_ADD_COMBINATION, OP_ASSIGNMENT) \
    OPERATOR_DEF("-=", OP_SUB_COMBINATION, OP_ASSIGNMENT) \
    OPERATOR_DEF("*=", OP_MULT_COMBINATION, OP_ASSIGNMENT) \
    OPERATOR_DEF("/=", OP_DIV_COMBINATION, OP_ASSIGNMENT) \
    \
    OPERATOR_DEF("==", OP_EQUAL, OP_EQUALITY) \
    OPERATOR_DEF("!=", OP_NOT_EQUAL, OP_EQUALITY) \
    \
    OPERATOR_DEF("<", OP_LESS_THAN, OP_RELATIONAL) \
    OPERATOR_DEF("<=", OP_LESS_EQUAL, OP_RELATIONAL) \
    OPERATOR_DEF(">", OP_GREATER_THAN, OP_RELATIONAL) \
    OPERATOR_DEF(">=", OP_GREATER_EQUAL, OP_RELATIONAL) \
    \
    OPERATOR_DEF("&&", OP_AND, OP_LOGIC) \
    OPERATOR_DEF("||", OP_OR, OP_LOGIC) \
    OPERATOR_DEF("!", OP_NOT, OP_LOGIC) \
    \
    OPERATOR_DEF(".", OP_ACCESS_DIRECT, OP_ACCESS) \
    OPERATOR_DEF("->", OP_ACCESS_POINTER, OP_ACCESS) \
    OPERATOR_DEF("::", OP_SCOPE_RESOLUTION, OP_ACCESS)

#define PATTERN_LIST \
    PATTERN_DEF(INT, LITERAL) \
    PATTERN_DEF(FLOAT, LITERAL) \
    PATTERN_DEF(STR_LIT, LITERAL) \
    PATTERN_DEF(CHAR_LIT, LITERAL) \
    PATTERN_DEF(IDENTIFIER, IDENTIFIER)

#define PUNCT_LIST \
    PUNCT_DEF(";", SEMI_COLON, PUNCT) \
    PUNCT_DEF("(", LEFT_PARENTHESIS, PUNCT) \
    PUNCT_DEF(")", RIGHT_PARENTHESIS, PUNCT) \
    PUNCT_DEF("{", LEFT_BRACE, PUNCT) \
    PUNCT_DEF("}", RIGHT_BRACE, PUNCT) \
    PUNCT_DEF("[", LEFT_BRACKET, PUNCT) \
    PUNCT_DEF("]", RIGHT_BRACKET, PUNCT) \
    PUNCT_DEF(",", COMMA, PUNCT) \
    PUNCT_DEF(":", COLON, PUNCT)

enum class TokenCategory {
    #define TYPE_DEF(type) type,
    TYPE_LIST
    #undef TYPE_DEF
};

enum class TokenType {
    UNKNOWN,
    #define PATTERN_DEF(token, cat) token,
    PATTERN_LIST
    #undef PATTERN_DEF
    #define PUNCT_DEF(str, token, cat) token,
    PUNCT_LIST
    #undef PUNCT_DEF
    #define KEYWORD_DEF(str, token, cat) token,
    KEYWORD_LIST
    #undef KEYWORD_DEF
    #define OPERATOR_DEF(str, token, cat) token,
    OPERATOR_LIST
    #undef OPERATOR_DEF
};

#endif //CPPCOMPILER_TOKENTYPE_H
